import { z } from 'zod';

/**
 * Request and response shapes for solves and practice sessions.
 *
 * Shared by the API and the client, so both validate against one definition.
 */

export const penaltySchema = z.enum(['none', 'plus2', 'dnf']);

export const practiceSessionSchema = z.object({
  id: z.uuid(),
  name: z.string(),
  createdAt: z.iso.datetime(),
  archivedAt: z.iso.datetime().nullable(),
});

export const createPracticeSessionRequestSchema = z.object({
  name: z.string().trim().min(1, 'A name is required').max(60),
});

export const solveSchema = z.object({
  id: z.uuid(),
  practiceSessionId: z.uuid(),
  scramble: z.string(),
  durationMs: z.number().int().nonnegative(),
  penalty: penaltySchema,
  comment: z.string().nullable(),
  solvedAt: z.iso.datetime(),
});

export const createSolveRequestSchema = z.object({
  /**
   * Generated by the client before the request is sent.
   *
   * This is what makes creating a solve idempotent: if the network drops after the
   * server commits but before the response arrives, the client retries with the same id
   * and the server recognises it rather than inserting a second copy. For a timer,
   * duplicating or losing a solve is the worst failure there is.
   */
  id: z.uuid(),
  practiceSessionId: z.uuid(),
  scramble: z.string().min(1).max(500),
  durationMs: z
    .number()
    .int('Durations are whole milliseconds')
    .nonnegative()
    // Twelve hours. Not a real solve, but a plausible result of a timer left running,
    // and an upper bound keeps absurd values out of the statistics.
    .max(12 * 60 * 60 * 1000),
  penalty: penaltySchema.default('none'),
  solvedAt: z.iso.datetime(),
  comment: z.string().max(500).nullable().default(null),
});

/**
 * Only the fields a solve can be corrected with after the fact.
 *
 * Deliberately excludes `durationMs` and `scramble`: the measurement is immutable, and
 * allowing it to be edited would turn the statistics into fiction.
 */
export const updateSolveRequestSchema = z
  .object({
    penalty: penaltySchema.optional(),
    comment: z.string().max(500).nullable().optional(),
  })
  .refine((body) => Object.keys(body).length > 0, {
    message: 'Provide at least one field to update',
  });

export const listSolvesQuerySchema = z.object({
  practiceSessionId: z.uuid().optional(),
  limit: z.coerce.number().int().min(1).max(100).default(50),
  /** Keyset cursor: the `solvedAt` of the last row already seen, plus its id. */
  cursor: z.string().optional(),
});

export type Penalty_Wire = z.infer<typeof penaltySchema>;
export type PracticeSession = z.infer<typeof practiceSessionSchema>;
export type CreatePracticeSessionRequest = z.infer<typeof createPracticeSessionRequestSchema>;
export type Solve = z.infer<typeof solveSchema>;
export type CreateSolveRequest = z.infer<typeof createSolveRequestSchema>;
export type UpdateSolveRequest = z.infer<typeof updateSolveRequestSchema>;
export type ListSolvesQuery = z.infer<typeof listSolvesQuerySchema>;
